name: example
description: examples of memoizer
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  memoizer_annotation: 1.0.0-nullsafety4
  mock_creator_annotation: ^1.0.2-nullsafety3

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.16.0-nullsafety.16
  memoizer_generator:
    path: ../memoizer_generator
  pedantic: ^1.9.0
  mock_creator_generator: ^1.0.14-nullsafety2
