name: example
description: examples of memoizer
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  memoizer_annotation:
    path: ../memoizer_annotation
  mock_creator_annotation:
    path: ../../mock_creator/mock_creator_annotation

dev_dependencies:
  build_runner: ^2.1.4
  test: ^1.18.2
  memoizer_generator:
    path: ../memoizer_generator
