targets:
  $default:
    builders:
      memoizer_generator|memoizer:
        enabled: true
 
builders:
  memoizer_generator:
    target: ":memoizer_generator"
    import: "package:memoizer_generator/memoizer_generator.dart"
    builder_factories: ["memoizerBuilder"]
    build_extensions: {".dart": [".x.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
