targets:
  $default:
    builders:
      memoizer_generator|memoizer:
        enabled: true
 
builders:
  memoizer_generator:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:memoizer_generator/memoizer_generator.dart"
    # Name of the function in the above library to call.
    builder_factories: ["memoizerBuilder"]
    # The mapping from the source extension to the generated file extension
    #   change extension in builder too
    build_extensions: {".dart": [".memo.dart"]}
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: source

#  memoizer_generator:
#    target: ":memoizer_generator"
#    import: "package:memoizer_generator/memoizer_generator.dart"
#    builder_factories: ["memoizerBuilder"]
#    build_extensions: {".dart": [".x.g.part"]}
#    auto_apply: dependents
#    build_to: cache
#    applies_builders: ["source_gen|combining_builder"]
