name: memoizer_generator
description: Creates a separate version of a function and extending memoize
version: 1.0.0-nullsafety5
homepage: https://github.com/atreeon/memoizer

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  meta: ^1.1.8
  analyzer_models: ^1.0.3
  build: ^1.2.2
  source_gen: ^0.9.4+7
  dartx_nullsafety: ^0.6.0-nullsaftety.0
  memoizer_annotation: 1.0.0-nullsafety4
  analyzer: '>=0.40.0 <0.42.0'

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.7.3
  test: ^1.11.1
