name: memoizer_generator
description: Creates a separate version of a function and extending memoize
version: 1.0.0-nullsafety13
homepage: https://github.com/atreeon/memoizer
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: '>=1.7.0 <=3.0.0'
  build: ^2.1.0
  source_gen: ^1.1.1
  dartx: ^0.6.0
  generator_common:
    path: ../../generator_common
  memoizer_annotation:
    path: ../memoizer_annotation

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^2.1.4
  test: ^1.18.2