name: memoizer_annotation
description: Creates a memoizable class from an existing class
version: 1.0.0-nullsafety

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.0-nullsafety.16
#  effective_dart: ^1.3.0

homepage: https://github.com/atreeon/memoizer
